providers = ["node"]

[phases.setup]
nixPkgs = ["...", "git-lfs"]

[phases.install]
cmds = [
  "git lfs install --local",
  "git lfs pull",
  "npm ci",
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx serve -s dist -l $PORT"
